package hibernate;
// Generated 13/04/2016 11:17:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Classificacao generated by hbm2java
 */
public class Classificacao  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private int idade;
     private Set filmes = new HashSet(0);

    public Classificacao() {
    }

	
    public Classificacao(String descricao, int idade) {
        this.descricao = descricao;
        this.idade = idade;
    }
    public Classificacao(String descricao, int idade, Set filmes) {
       this.descricao = descricao;
       this.idade = idade;
       this.filmes = filmes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public int getIdade() {
        return this.idade;
    }
    
    public void setIdade(int idade) {
        this.idade = idade;
    }
    public Set getFilmes() {
        return this.filmes;
    }
    
    public void setFilmes(Set filmes) {
        this.filmes = filmes;
    }




}


