package hibernate;
// Generated 13/04/2016 11:17:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private int idade;
     private String genero;
     private String cpf;
     private String rg;
     private String telefone;
     private String endereco;
     private Set emprestimos = new HashSet(0);
     private Set reservas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nome, int idade, String genero, String rg, String telefone, String endereco) {
        this.nome = nome;
        this.idade = idade;
        this.genero = genero;
        this.rg = rg;
        this.telefone = telefone;
        this.endereco = endereco;
    }
    public Cliente(String nome, int idade, String genero, String cpf, String rg, String telefone, String endereco, Set emprestimos, Set reservas) {
       this.nome = nome;
       this.idade = idade;
       this.genero = genero;
       this.cpf = cpf;
       this.rg = rg;
       this.telefone = telefone;
       this.endereco = endereco;
       this.emprestimos = emprestimos;
       this.reservas = reservas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getIdade() {
        return this.idade;
    }
    
    public void setIdade(int idade) {
        this.idade = idade;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Set getEmprestimos() {
        return this.emprestimos;
    }
    
    public void setEmprestimos(Set emprestimos) {
        this.emprestimos = emprestimos;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


