package hibernate;
// Generated 13/04/2016 11:17:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Emprestimo generated by hbm2java
 */
public class Emprestimo  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private Filme filme;
     private Boolean confPagamento;
     private Date dtEntrada;
     private Date dtRetirada;
     private Float valorPago;

    public Emprestimo() {
    }

    public Emprestimo(Cliente cliente, Filme filme, Boolean confPagamento, Date dtEntrada, Date dtRetirada, Float valorPago) {
       this.cliente = cliente;
       this.filme = filme;
       this.confPagamento = confPagamento;
       this.dtEntrada = dtEntrada;
       this.dtRetirada = dtRetirada;
       this.valorPago = valorPago;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Filme getFilme() {
        return this.filme;
    }
    
    public void setFilme(Filme filme) {
        this.filme = filme;
    }
    public Boolean getConfPagamento() {
        return this.confPagamento;
    }
    
    public void setConfPagamento(Boolean confPagamento) {
        this.confPagamento = confPagamento;
    }
    public Date getDtEntrada() {
        return this.dtEntrada;
    }
    
    public void setDtEntrada(Date dtEntrada) {
        this.dtEntrada = dtEntrada;
    }
    public Date getDtRetirada() {
        return this.dtRetirada;
    }
    
    public void setDtRetirada(Date dtRetirada) {
        this.dtRetirada = dtRetirada;
    }
    public Float getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(Float valorPago) {
        this.valorPago = valorPago;
    }




}


