package hibernate;
// Generated 13/04/2016 11:17:37 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Filme generated by hbm2java
 */
public class Filme  implements java.io.Serializable {


     private Integer id;
     private Classificacao classificacao;
     private Diretor diretor;
     private Genero genero;
     private Produtora produtora;
     private String nome;
     private Date dtEstreia;
     private Set reservas = new HashSet(0);
     private Set emprestimos = new HashSet(0);

    public Filme() {
    }

    public Filme(Classificacao classificacao, Diretor diretor, Genero genero, Produtora produtora, String nome, Date dtEstreia, Set reservas, Set emprestimos) {
       this.classificacao = classificacao;
       this.diretor = diretor;
       this.genero = genero;
       this.produtora = produtora;
       this.nome = nome;
       this.dtEstreia = dtEstreia;
       this.reservas = reservas;
       this.emprestimos = emprestimos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Classificacao getClassificacao() {
        return this.classificacao;
    }
    
    public void setClassificacao(Classificacao classificacao) {
        this.classificacao = classificacao;
    }
    public Diretor getDiretor() {
        return this.diretor;
    }
    
    public void setDiretor(Diretor diretor) {
        this.diretor = diretor;
    }
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }
    public Produtora getProdutora() {
        return this.produtora;
    }
    
    public void setProdutora(Produtora produtora) {
        this.produtora = produtora;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDtEstreia() {
        return this.dtEstreia;
    }
    
    public void setDtEstreia(Date dtEstreia) {
        this.dtEstreia = dtEstreia;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }
    public Set getEmprestimos() {
        return this.emprestimos;
    }
    
    public void setEmprestimos(Set emprestimos) {
        this.emprestimos = emprestimos;
    }




}


